export const LIST_CHECK_INS_SUCCESS = 'checkIn/LIST_CHECK_INS_SUCCESS';
export const GET_NEARBY_CHECK_INS_SUCCESS = 'checkIn/GET_NEARBY_CHECK_INS_SUCCESS';

export const RESET_CHECK_IN_LIST = 'checkIn/RESET_CHECK_IN_LIST';
export const SET_SELECTED_CHECK_IN = 'checkIn/SET_SELECTED_CHECK_IN';

export const RESET_SELECTED_CHECK_IN = 'checkIn/RESET_SELECTED_CHECK_IN';
export const SET_SELECTED_LOCATION = 'checkIn/SET_SELECTED_LOCATION';

export const RESET_SELECTED_LOCATION = 'checkIn/RESET_SELECTED_LOCATION';
