export const LOGIN_USER_REQUEST = 'authentication/LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'authentication/LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'authentication/LOGIN_USER_ERROR';

export const GET_CURRENT_LOCATION_REQUEST = 'location/GET_CURRENT_LOCATION_REQUEST';
export const GET_CURRENT_LOCATION_SUCCESS = 'location/GET_CURRENT_LOCATION_SUCCESS';
export const GET_CURRENT_LOCATION_ERROR = 'location/GET_CURRENT_LOCATION_ERROR';

export const GET_NEARBY_REQUEST = 'places/GET_NEARBY_REQUEST';
export const GET_NEARBY_SUCCESS = 'places/GET_NEARBY_SUCCESS';
export const GET_NEARBY_ERROR = 'places/GET_NEARBY_ERROR';
